"use client";
import { useState } from "react";
import { ALTANA_TESTNET_EXPLORER, ALTANA_TESTNET_USD_FAUCET } from "@/lib/altana-browser";
import { useAltanaWallet } from "./altana-wallet-provider";

export function AltanaWalletPanel() {
  const wallet = useAltanaWallet(); const [transactionHash, setTransactionHash] = useState("");
  async function requestTokens() { try { setTransactionHash((await wallet.requestTestTokens()) || "Submitted through Altana relay"); } catch {} }
  return <div className="overview-grid">
    <section className="panel detail-panel"><div className="panel-title"><h2>Altana Passkey Wallet</h2><span>BSC Mainnet + Testnet</span></div><div className="wallet-panel-body">{wallet.session ? <><dl className="detail-list compact-list"><div><dt>Commerce wallet</dt><dd><a href={`${ALTANA_TESTNET_EXPLORER}/address/${wallet.session.wallet.address}`} target="_blank" rel="noreferrer"><code>{wallet.session.wallet.address}</code></a></dd></div><div><dt>Mainnet BNB</dt><dd>{wallet.balance?.mainnetNative ?? "Loading…"}</dd></div><div><dt>Mainnet $U</dt><dd>{wallet.balance?.mainnetPaymentToken ?? "Loading…"}</dd></div><div><dt>Testnet tBNB</dt><dd>{wallet.balance?.native ?? "Loading…"}</dd></div><div><dt>Testnet $U</dt><dd>{wallet.balance?.paymentToken ?? "Loading…"}</dd></div></dl><div className="button-row"><button className="primary-action" disabled={wallet.busy} onClick={() => void wallet.refreshBalance()}>Refresh balances</button><button disabled={wallet.busy} onClick={wallet.disconnect}>Forget local session</button></div></> : <><p>This is Altana’s official browser wallet path. One passkey controls the same wallet address on BSC Mainnet and Testnet; AgentDB never receives or exports a private key.</p><div className="button-row"><button className="primary-action" disabled={wallet.busy} onClick={() => void wallet.createWallet()}>Create passkey wallet</button><button disabled={wallet.busy} onClick={() => void wallet.recoverWallet()}>Recover with passkey</button></div></>}{wallet.error && <div className="notice warning-notice">{wallet.error}</div>}</div></section>
    <section className="panel detail-panel"><div className="panel-title"><h2>Testnet Funding</h2><span>Official faucets only</span></div><div className="wallet-panel-body"><ol><li>Fund the public Altana address with tBNB using the official BNB Chain faucet.</li><li>Request 10 testnet $U from Altana’s official ERC-8183 faucet (30-minute cooldown).</li></ol><div className="button-row"><a className="primary-action button-link" href="https://www.bnbchain.org/en/testnet-faucet" target="_blank" rel="noreferrer">Open tBNB faucet</a><button disabled={!wallet.session || wallet.busy} onClick={() => void requestTokens()}>Request 10 testnet $U</button></div><p className="subtle">$U faucet: <code>{ALTANA_TESTNET_USD_FAUCET}</code></p>{transactionHash && <div className="notice success-notice">Request result: <code>{transactionHash}</code></div>}</div></section>
  </div>;
}
